---
- name: selinux disabled
  selinux: policy=targeted state=disabled
  tags:
    - common
    - selinux
  notify: reboot system

- name: package install
  yum: pkg={{ item }} state=latest
  with_items:
    - curl-devel
    - expat-devel
    - gettext-devel
    - openssl-devel 
    - zlib-devel
    - perl-ExtUtils-MakeMaker
    - unzip
  tags:
    - common
    - install
 
- name: git install
  include: git.yml
  tags: common

- name: java install
  include: java.yml
  tags: common

- name: check and create application directory
  file: path="{{ application_dir }}" state=directory owner={{ ansible_env.SUDO_USER }} group={{ ansible_env.SUDO_USER }} mode=0755
  tags:
    - common
    - mandala

- name: .vimrc settings
  copy: src=.vimrc dest="{{ item.home_dir }}" mode=0644 
        owner={{ item.user_name }} group={{ item.user_name }} backup=yes
  with_items:
    - { home_dir: '/root/',                              user_name: 'root' }
    - { home_dir: '/home/{{ ansible_env.SUDO_USER }}/',  user_name: '{{ ansible_env.SUDO_USER }}' }
  tags:
    - common
    - vim

- name: source .vimrc
  shell: source {{ item }}/.vimrc
  with_items:
    - /root
    - /home/{{ ansible_env.SUDO_USER }}
  tags:
    - common
    - vim
