---
- name: reboot system
  shell: sleep 2 && shutdown -r now 
  async: 1
  poll: 0
  tags: common

- name: wait for SSH port down
  local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped
  tags:
    - common

- name: wait for SSH port up
  wait_for: host={{ inventory_hostname }} port=22 state=started delay=30
  delegate_to: 127.0.0.1
  tags:
    - common
