---
- name: "create init script"
  template: src=init.d.php-fpm.j2 dest=/etc/init.d/php-fpm mode="u=rwx,g=r,o=r"
  tags: 
    - php
    - php-fpm

- name: "create config file"
  template: src=php-fpm.conf.j2 dest=/usr/local/etc/php-fpm.conf
  tags: 
    - php
    - php-fpm
  notify: restart php-fpm

- name: create socket directory
  file: path=/var/lib/php state=directory owner=nginx group=nginx recurse=yes
  tags:
    - php
    - php-fpm

- name: add php-fpm to systemd
  template: src=php-fpm.service.j2 dest=/etc/systemd/system/php-fpm.service
  tags: 
    - php
    - php-fpm

- name: ensure php-fpm is running (and enable it at boot)
  systemd: name=php-fpm state=started daemon_reload=yes enabled=yes
  tags: 
    - php
    - php-fpm
