---
- name: install tasks for Local Server
  hosts: local
  become: yes
  roles:
    - common
    - gradle
    - fabric
    - nginx
    - go
    - grpc
    - grpc/go
    - php
    - php/phalcon
    - php/php-fpm
    - php/pecl-memcached
    - php/zip

- name: install tasks for local user
  hosts: local
  become: no
  roles:
    - ruby
    - nodejs
    - nodejs/raml
